FinanceCalculators/Controllers/RefinancingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using PartyInvites.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace PartyInvites.Controllers
{
    public class RefinancingController : Controller
    {
        [HttpGet]
        public IActionResult RefinanceCalc()
        {
            return View();
        }

        //public IActionResult Index(LeasingModel LeasingModel, string calculate)
        [HttpPost]

        public IActionResult RefinanceCalc(string CreditAmount, string InterestRatePercent, string CreditTermMonths, string NumberOfPaymentsMade, string EarlyRepaymentTax, string NewCreditInterest, string NewCreditInitialTaxesPecent)
        {
            try
            {
                /* verifies all inputs are positive */
                if (int.Parse(CreditAmount) < 0 || int.Parse(InterestRatePercent) < 0 || int.Parse(CreditTermMonths) < 0 || int.Parse(NumberOfPaymentsMade) < 0 || int.Parse(EarlyRepaymentTax) < 0 ||
                    int.Parse(NewCreditInterest) < 0 || int.Parse(NewCreditInitialTaxesPecent) < 0)
                {
                    ViewBag.NegNumError = "Please input positive numbers";
                }

                else
                {
                    /* calculates if InitialFee has been selected as a percentage */
                    /*if (FlatOrPercent == false)
                    {*/

                    double creditAmountDouble = double.Parse(CreditAmount);
                    double interestRateDouble = double.Parse(InterestRatePercent);
                    double creditTermMonthsDouble = double.Parse(CreditTermMonths);
                    double numberOfPaymentsMadeDouble = double.Parse(NumberOfPaymentsMade);
                    double earlyRepaymentTaxDouble = double.Parse(EarlyRepaymentTax);
                    double totalPaymentsMade = 0;

                    double newCreditInterestDouble = double.Parse(NewCreditInterest);
                    double newCreditInitialTaxesPecentDouble = double.Parse(NewCreditInitialTaxesPecent);
                    double newCreditPayment = 0;

                    double monthlyPayment = 0;
                    double realPayemnt = 0;

                    /*Лихви*/
                    double interestRate = interestRateDouble / 100;
                    double interesterRateNew = newCreditInterestDouble / 100;
                    double interestAmount = 0;

                    /*Оставащ срок*/
                    /* needs to be validated or NPer error */
                    double newTerm = creditTermMonthsDouble - numberOfPaymentsMadeDouble;

                    /*Такса за предсрочно погасяване*/
                    double remainingDueAmount = creditAmountDouble;

                    for (double i = 0; i <= numberOfPaymentsMadeDouble; i++)
                    {
                        remainingDueAmount -= realPayemnt;
                        interestAmount = remainingDueAmount * (interestRate / 12);
                        monthlyPayment = Microsoft.VisualBasic.Financial.Pmt(interestRate / 12, creditTermMonthsDouble, -creditAmountDouble);
                        realPayemnt = monthlyPayment - interestAmount;
                    }

                    earlyRepaymentTaxDouble = remainingDueAmount * (earlyRepaymentTaxDouble / 100);

                    /*Месечна вноска за текущ кредит*/
                    double monthlyPaymentCurrentCredit = Microsoft.VisualBasic.Financial.Pmt(interestRate / 12, creditTermMonthsDouble, -creditAmountDouble);

                    /*Общо изплатени за текущ кредит*/
                    totalPaymentsMade = monthlyPaymentCurrentCredit * numberOfPaymentsMadeDouble;

                    /*Месечна вноска за нов кредит*/
                    newCreditPayment = Microsoft.VisualBasic.Financial.Pmt(newCreditInterestDouble / 12, newTerm, -remainingDueAmount);

                    /*Общо изплатени за нов кредит*/
                    double newTotalPaymentsMade = (newCreditPayment * newTerm) + earlyRepaymentTaxDouble + (creditAmountDouble * (newCreditInitialTaxesPecentDouble / 100) + double.Parse(NewCreditInitialTaxesPecent));

                    /*Спестявания от вноски*/
                    double savingsPayments = monthlyPaymentCurrentCredit - newCreditPayment;

                    /*Спестявания от общо изплатени*/
                    double savingsTotal = totalPaymentsMade - newTotalPaymentsMade;

                    /*изходни*/
                    ViewBag.interestRate = Math.Round(interestRateDouble, 2, MidpointRounding.AwayFromZero);

                    //Math.Round(newTotalPaymentsMade, 2, MidpointRounding.AwayFromZero);

                    ViewBag.interestRateNew = Math.Round(newCreditInterestDouble, 2, MidpointRounding.AwayFromZero);

                    ViewBag.creditTermOld = Math.Round(creditTermMonthsDouble, 2, MidpointRounding.AwayFromZero);
                    ViewBag.creditTermNew = Math.Round(newTerm, 2, MidpointRounding.AwayFromZero);

                    ViewBag.earlyRepaymentTax = Math.Round(earlyRepaymentTaxDouble, 2, MidpointRounding.AwayFromZero);

                    ViewBag.monthlyPaymentOld = Math.Round(monthlyPaymentCurrentCredit, 2, MidpointRounding.AwayFromZero);
                    ViewBag.monthlyPaymentNew = Math.Round(newCreditPayment, 2, MidpointRounding.AwayFromZero);

                    ViewBag.monthlySavingsTotal = Math.Round((totalPaymentsMade - newTotalPaymentsMade), 2, MidpointRounding.AwayFromZero);

                    ViewBag.totalPaidOld = Math.Round(totalPaymentsMade, 2, MidpointRounding.AwayFromZero);
                    ViewBag.totalPaidNew = Math.Round(newTotalPaymentsMade, 2, MidpointRounding.AwayFromZero);

                    /* TODO: Спесявания - трета колона - да изчислява разликите между нов и стар за всяка стойност*/
                    ViewBag.savingsOnMonthly = monthlyPaymentCurrentCredit - newCreditPayment;

                    ViewBag.savingsOnTotal = Math.Round(totalPaymentsMade - newTotalPaymentsMade, 2, MidpointRounding.AwayFromZero); 


                    /*return View();*/

                    /* calculates if InitialFee has been selected as a flat value 
                    else
                    {
                        double leaseAmountDouble = double.Parse(LeaseAmount);
                        double initialPaymentDouble = double.Parse(InitialPayment);
                        double leasePeriodMonthsDouble = double.Parse(LeasePeriodMonths);
                        double monthlyPaymentsDouble = double.Parse(MonthlyPayments);
                        double initialFilingFeeDouble = 250;

                        double totalTaxes = initialFilingFeeDouble;

                        double totalPaid = totalTaxes + initialPaymentDouble + monthlyPaymentsDouble * leasePeriodMonthsDouble;

                        ViewBag.totalPaidWithTaxes = totalPaid + totalTaxes;
                        ViewBag.totalTaxes = totalTaxes;

                        double oneTooMany = ViewBag.totalPaidWithTaxes - leaseAmountDouble;
                        /*Изчислявам го като процен оскъпяване спрямо цената на стоката****
                        ViewBag.totalYearlySpendingPercent = (oneTooMany / totalPaid) * 100;


                        return View();
                    }*/
                }


            }
            catch (ArgumentNullException ex)
            {
                string emptyValueError = ex.Message;
                ViewBag.ErrorMessageEmpty = "Please input a number and try again";
            }
            catch (FormatException ex)
            {
                string formatError = ex.Message;
                ViewBag.ErrorFormat = "Please enter numeric values only and try again";
            }

            return View();
            /* if (lease == "calculate")
            {
                //LeasingModel.LeasingTotalResult = LeasingModel.LeasingValue1 + LeasingModel.LeasingValue2 + LeasingModel.LeasingValue3;
            }
            else
            {
               // LeasingModel.LeasingTotalResult = LeasingModel.LeasingValue1 + LeasingModel.LeasingValue2 - LeasingModel.LeasingValue3;
            }

            return View(LeasingModel);*/

        }

    }
}

FinanceCalculators/Views/Refinancing/RefinanceCalc.cshtml
<!DOCTYPE html>
@model PartyInvites.Models.RefinanceModel
<!--@{ Layout = null; }-->
<!--TODO: InitialFilingFee flat or percent???; Outputs not done; HTML validation;-->

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <title>Refinancing Calculator</title>

    <link rel="stylesheet" href="/css/creditcal.css"><!--leasingcal.css?-->
    <link rel="stylesheet" href="/css/styles.css" />
    <!--<link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" /> -->

    <link rel="icon" href="/Content/Assets/head-logo.jpeg" type="image/png">
</head>


<body>

    <div class="navigation">
        <div class="main-logo">
            <a href="http://localhost:5000"><img src="/Content/Assets/logo.png" class="main-logo-image"></a>
        </div>
    </div>

    </br>
    </br>

    <label for="section-title" class="section-title">Калкулатор за рефинансиране</label>
    </br>
    <label for="section-mini-title" class="section-mini-title">Пресметнете дали рефинансирането на задълженията Ви е изгодно</label>

    </br>
    </br>
    <!--Refinancing Calculator Fields-->
    <div class="main-container">
        <label for="section-title" class="section-title">Настоящ кредит</label>
        <!--below <form> only concernes View <-> Controller relationship-->
        <form asp-controller="Refinancing" asp-action="RefinanceCalc" method="post" class="m-2">
            <div class="float-container">
                <div class="float-child-left">
                    <div class="input-wrapper">
                        <input type="number" asp-for="CreditAmount" asp-controller="Refinancing" asp-action="RefinanceCalc" name="CreditAmount" placeholder="Размер на кредита*" required id="size" min="100" max="100000000"><br>
                    </div>
                </div>

                <div class="float-child-right">
                    <div class="input-wrapper">
                        <input type="number" asp-for="InterestRatePercentage" asp-controller="Refinancing" asp-action="RefinanceCalc" name="InterestRatePercent" placeholder="Лихва (%)*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>

                <div class="float-child-left">
                    <div class="input-wrapper">
                        <input type="number" asp-for="CreditTermMonths" asp-controller="Refinancing" asp-action="RefinanceCalc" name="CreditTermMonths" placeholder="Срок на кредита (месеци)*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>

                <div class="float-child-right">
                    <div class="input-wrapper">
                        <input type="number" asp-for="NumberOfPaymentsMade" asp-controller="Refinancing" asp-action="RefinanceCalc" name="NumberOfPaymentsMade" placeholder="Брой на направените вноски*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>

                <div class="dropdown-child">
                    <div class="input-wrapper">
                        <input type="number" asp-for="EarlyRepaymentTax" asp-controller="Refinancing" asp-action="RefinanceCalc" name="EarlyRepaymentTax" placeholder="Такса за предсрочно погасяване*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>
            </div>

            <label for="section-title" class="section-title">Нов кредит</label>

            <div class="float-container">

                <div class="float-child-left">
                    <div class="input-wrapper">
                        <input type="number" asp-for="InitialTaxes" asp-controller="Refinancing" asp-action="RefinanceCalc" name="NewCreditInitialTaxesPecent" placeholder="Първоначални такси*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>

                <div class="float-child-right">
                    <select asp-for="InitialTaxesFlatOrPercentage" name="ApplicationFeeFlatOrPercentage" asp-controller="Refinancing" asp-action="RefinanceCalc" class="selector">
                        <option value="true">валута</option>
                        <option value="false">%</option>
                    </select>
                </div>

                <div class="dropdown-child">
                    <div class="input-wrapper">
                        <input type="number" asp-for="InterestRate" asp-controller="Refinancing" asp-action="RefinanceCalc" name="NewCreditInterest" placeholder="Лихва*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>
            </div>

            <!--onclick="myFunction()"-->
            <div class="button-container" formmethod="post" type="submit" id="lease" value="lease" name="calculate">
                <button asp-controller="Refinancing" asp-action="RefinanceCalc" formmethod="post" type="submit" class="calculate-button" id="Refinancing" value="Refinancing" name="Refinancing">Изчисли</button>
            </div>

        </form>
    </div>

    <!--style="display: none-->
    <div id="result-table" class="result-table">

        <label for="section-mini-title" class="section-mini-title">Сумарни разходи</label>
        </br>

        <table>
            <tr>
                <td>Резултат</td>
                <td>Текущ кредит</td>
                <td>Нов кредит</td>
                <td>+/- Спестявания</td>
            </tr>
            <tr>
                <td>Лихва</td>
                <td>@ViewBag.interestRate</td>
                <td>@ViewBag.interestRateNew</td>
                <td></td>
            </tr>
            <tr>
                <td>Срокове на кредитите</td>
                <td>@ViewBag.creditTermOld</td>
                <td>@ViewBag.creditTermNew</td>
                <td></td>
            </tr>
            <tr>
                <td>Такса за предсрочно погасяване</td>
                <td>@ViewBag.earlyRepaymentTax</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Месечна вноска</td>
                <td>@ViewBag.monthlyPaymentOld</td>
                <td>@ViewBag.monthlyPaymentNew</td>
                <td>@ViewBag.monthlySavingsTotal</td>
            </tr>
            <tr>
                <td>Общо изплатени</td>
                <td>@ViewBag.totalPaidOld</td>
                <td>@ViewBag.totalPaidNew</td>
                <td>@ViewBag.savingsOnTotal</td>
            </tr>
        </table>
    </div>
    </div>
    <br>

    <!--Margin to be removed-->
    <div class="section-footer-description" style="margin-top: 150px;">
        <label>
            * Задължителни полетa </br> </br>
            C пoмoщтa нa ĸaлĸyлaтopa зa peфинaнcиpaнe нa ĸpeдити мoжeтe дa изчиcлитe ĸoлĸo биxтe cпecтили/изгyбили, aĸo peшитe дa peфинaнcиpaтe, т.e. дa изтeглитe нoв ĸpeдит, зa дa пoгacитe cтapo ĸpeдитнo зaдължeниe.
            Зa цeлтa тpябвa дa въвeдeтe cлeднитe дaнни зa нacтoящия Bи ĸpeдит – paзмep, гoдишeн лиxвeн пpoцeнт, cpoĸ нa ĸpeдитa, бpoй нa нaпpaвeнитe внocĸи пo нeгo дo мoмeнтa, ĸaĸтo и paзмepa нa нaĸaзaтeлнaтa лиxвa зa пpeдcpoчнo пoгacявaнe.</br></br> Heoбxoдимитe дaнни зa нoвият ĸpeдит ca лиxвeн пpoцeнт и дължими тaĸcи и ĸoмиcиoнни нa бaнĸaтa пo oтпycĸaнeтo нa ĸpeдитa.
            Kaлĸyлaтopът изчиcлявa двe cтoйнocти, пo ĸoитo мoжeтe дa ce opиeнтиpaтe дaли peфинaнcиpaнeтo e изгoднo зa Bac – paзлиĸa мeждy мeceчнитe внocĸи пo двaтa ĸpeдитa и мeждy oбщo изплaтeнитe cyми.
        </label>
    </div>

    <div class="footer">

        <div class="footer-column" style="padding: 50px 0px 0px 0px;">
            <img src="/Content/Assets/second-logo.png">
            <p classs="main-text"> ул. “Монтевидео” 21, 1618 <br> ж.к. Овча Купел 2, Sofia</p>
        </div>

        <div class="footer-column" style="padding: 20px 0px 0px 0px;">
            <img src="/Content/Assets/footer-illustration.png" class="footer-image">
        </div>

        <div class="footer-column" style="padding: 200px 0px 0px 0px;">
            <p classs="main-text">© 2020 Нов Български Университет</p>
        </div>
    </div>

    <!--
    <script>

        function myFunction() {

            console.log("Lead me to the BE , calculate result & come back.")

            var tb = document.getElementById("result-table");

            if (tb.style.display == "none") {
                tb.style.display = "grid";
            }
        }

    </script>
        -->
</body>

</html>