FinanceCalculators/Controllers/CreditController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.VisualBasic;
using PartyInvites.Models;

namespace PartyInvites.Controllers
{
    public class CreditController : Controller
    {
        [HttpGet]
        public IActionResult CreditCalc()
        {
            return View();
        }

        [HttpPost]
        /*TODO: Set float point precision for outputs; Go over validation and required fields; Fix calc algorythm*/
        //public IActionResult Index(LeasingModel LeasingModel, string calculate)
        public IActionResult CreditCalc(double CreditAmount, double CreditTermMonths, double InterestRatePercentage, bool? AnualOrDecreasingInstallments, double? PromotionalPeriodMonths, double? PromotionalInterestPercentage,
            double? GratisPeriodMonths, double? ApplicationFee, bool? ApplicationFeeFlatOrPercentage, double? FilingFee, bool? FilingFeeFlatOrPercentage, double? OtherFee,
            bool? OtherFeeFlatOrPercentage, double? AnnualAdminFee, bool? AnnualAdminFeeFlatOrPercentage, double? OtherAnnualFee, bool? OtherAnnualFeeFlatOrPercentage, double? MonthlyAdminFee, double? OtherMonthlyFee,
            bool? MonthlyAdminFeeFlatOrPercentage, bool? OtherMonthlyFeeFlatOrPercentage, double monthlyInterest, double monthlyTax, double yearlyTax, double paidBackAlready, double montlyInterest)
        {
            try
            {
                CreditModel cm = new CreditModel(
                        creditAmount: CreditAmount,
                        creditTermMonths: CreditTermMonths,
                        interestRatePercentage: InterestRatePercentage,
                        anualOrDecreasingInstallments: AnualOrDecreasingInstallments,
                        promotionalPeriodMonths: PromotionalPeriodMonths,
                        promotionalInterestPercentage: PromotionalInterestPercentage,
                        gratisPeriodMonths: GratisPeriodMonths,
                        applicationFee: ApplicationFee,
                        applicationFeeFlatOrPercentage: ApplicationFeeFlatOrPercentage,
                        filingFee: FilingFee,
                        filingFeeFlatOrPercentage: FilingFeeFlatOrPercentage,
                        otherFee: OtherFee,
                        otherFeeFlatOrPercentage: OtherFeeFlatOrPercentage,
                        annualAdminFee: AnnualAdminFee,
                        annualAdminFeeFlatOrPercentage: AnnualAdminFeeFlatOrPercentage,
                        otherAnnualFee: OtherAnnualFee,
                        otherAnnualFeeFlatOrPercentage: OtherAnnualFeeFlatOrPercentage,
                        monthlyAdminFee: MonthlyAdminFee,
                        monthlyAdminFeeFlatOrPercentage: MonthlyAdminFeeFlatOrPercentage,
                        otherMonthlyFee: OtherMonthlyFee,
                        otherMonthlyFeeFlatOrPercentage: OtherMonthlyFeeFlatOrPercentage
                  );

                // Проверката не е нужна, всички числа се валидират през HTML, при въвеждане на негативно ще бъде показан popup гласящ
                // че това е невъзможно

                /* verifies all inputs are positive */
                //if (cm.CreditAmount < 0 || int.Parse(CreditTermMonths) < 0 || int.Parse(InterestRatePercentage) < 0 || int.Parse(PromotionalPeriodMonths) < 0 || int.Parse(PromotionalInterestPercentage) < 0
                //    || int.Parse(GratisPeriodMonths) < 0 || int.Parse(ApplicationFee) < 0 || int.Parse(FilingFee) < 0 || int.Parse(OtherFee) < 0 || int.Parse(AnnualAdminFee) < 0 || int.Parse(OtherAnnualFee) < 0
                //    || int.Parse(MonthlyAdminFee) < 0 || int.Parse(OtherMonthlyFee) < 0)
                //{
                //    ViewBag.NegNumError = "Моля въведете позитивни стойности";
                //}

                    
                    /* calculates if InitialFee has been selected as a percentage */

                    /* If installments are Annual */
                    if (cm.AnualOrDecreasingInstallments == true)
                    {
                        cm.InterestRatePercentage /= 100;
                        double remainingDueAmount = cm.CreditAmount;
                        cm.PromotionalInterestPercentage /= 100;

                    /*int InterestRatePercent = int.Parse(InterestRatePercentage);*/
                    /*double monthlyInterest;*/

                    /*Първоначални такси = Такса кандидатстване + Такса обработка + Други такси*/
                    double initialTax = (double)(cm.ApplicationFee + cm.FilingFee + cm.OtherFee);

                        /*Такса кандидатстване = Размера на кредита * Такса кандидатстване/100 (ако е в проценти)*/
                        if (cm.ApplicationFeeFlatOrPercentage == false)
                        {
                            cm.ApplicationFee = cm.CreditAmount * cm.ApplicationFee / 100;
                        }
                        /*Такса обработка = Размера на кредита * Такса обработка/100 (ако е в проценти)*/
                        if (FilingFeeFlatOrPercentage == false)
                        {
                            cm.FilingFee = cm.CreditAmount * cm.FilingFee / 100;
                        }
                        /*Други такси = Размера на кредита * Други такси/100 (ако е в проценти)*/
                        if (OtherFeeFlatOrPercentage == false)
                        {
                            cm.OtherFee = cm.CreditAmount * cm.OtherFee / 100;
                        }

                        /*========================================================================================================================*/
                        /*==============================================probl relocate============================================================*/
                        /*========================================================================================================================*/

                        /*Годишни такси = Годишна такса управление + Други годишни такси (таксуват се при първа вносна главница от следващата година)*/
                        double realAnnualTax = (double)(cm.AnnualAdminFee + cm.OtherAnnualFee);

                        /*Годишна такса управление = входа (ако е във валута)*/
                        /*Годишна такса управление = Първата вносна главница на следващата година * входа/100 (ако е в проценти)*/
                        if (AnnualAdminFeeFlatOrPercentage == false)
                        {
                            /*TODO ot sledvashta godina*/
                            cm.AnnualAdminFee = cm.CreditAmount * cm.AnnualAdminFee / 100;
                        }

                        /*Други годишни такси = Първата вносна главница на следващата година * входа/100 (ако е в проценти)*/
                        if (OtherAnnualFeeFlatOrPercentage == false)
                        {
                            /*TODO ot sledvashta godina*/
                            cm.OtherAnnualFee = cm.CreditAmount * cm.AnnualAdminFee / 100;
                        }

                        /*Месечни такси = Месечна такса управление + Други месечни такси (таксуват се всеки месец)*/
                        double realMonthlyTax = (double)(cm.MonthlyAdminFee + cm.OtherMonthlyFee);

                        if (MonthlyAdminFeeFlatOrPercentage == false)
                        {
                            /*TODO creditAmount/creditTermMonths =SHOULD BE= VnosnaGlavnitsa/monthlyPayback*/
                            cm.MonthlyAdminFee = (cm.CreditAmount / cm.CreditTermMonths) * cm.MonthlyAdminFee / 100;
                        }

                        if (OtherMonthlyFeeFlatOrPercentage == false)
                        {
                            /*TODO creditAmount/creditTermMonths == VnosnaGlavnitsa/monthlyPayback*/
                            cm.OtherMonthlyFee = (cm.CreditAmount / cm.CreditTermMonths) * cm.OtherMonthlyFee / 100;
                        }

                        /*========================================================================================================================*/
                        /*========================================================================================================================*/
                        /*========================================================================================================================*/

                        while (cm.CreditTermMonths > 0)
                        {
                            /*if still in Gratis Period*/
                            while (cm.GratisPeriodMonths > 0)
                            {
                                /*TODO check if gratis period does not surpass credit term as validation*/

                                cm.GratisPeriodMonths--;
                                cm.CreditTermMonths--;
                            }

                            /*Ако все още планът е в промоционалния период, то:*/
                            if (cm.PromotionalPeriodMonths != 0)
                            {
                                /*Месечната лихва = Остатъкът по главницата * Промоционалната лихва/12 */
                                monthlyInterest = (double)(remainingDueAmount * cm.PromotionalInterestPercentage / 12);

                                cm.PromotionalPeriodMonths--;
                            }
                            /*Ако планът вече не е в промоционален период, то:*/
                            else
                            {
                                /* Месечната лихва = Остатъкът по главницата * Лихвата / 12*/
                                montlyInterest = remainingDueAmount * cm.InterestRatePercentage / 12;
                            }


                            /*Месечна вноска = Financial.Pmt(Промоционалната лихва / 12, Срокът месеци - текущия месец, -Остатъкът по главницата)(за анюитетни вноски)*/

FinanceCalculators/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PartyInvites.Models;
using System.Linq;

namespace PartyInvites.Controllers {
    public class HomeController : Controller {
        
        public IActionResult Index() {
            return View();
        }

        [HttpGet]
        public ViewResult RefinanceCalc()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult RefinanceCalc(RefinanceModel RefinancingModel, string calculate)
        {

            return RefinanceCalc();
        }
         
    }
}

FinanceCalculators/Controllers/LeasingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using PartyInvites.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace PartyInvites.Controllers
{
    public class LeasingController : Controller
    {
        [HttpGet]
        public IActionResult LeaseCalc()
        {
            return View();
        }

        [HttpPost]
        //public IActionResult Index(LeasingModel LeasingModel, string calculate)
        public IActionResult LeaseCalc(string LeaseAmount, string InitialPayment, string LeasePeriodMonths, string MonthlyPayments, string InitialFilingFee, bool FlatOrPercent)
        {
            try
            {
                /* verifies all inputs are positive */
                if (int.Parse(LeaseAmount) < 0 || int.Parse(InitialPayment) < 0 || int.Parse(LeasePeriodMonths) < 0 || int.Parse(MonthlyPayments) < 0 || int.Parse(InitialFilingFee) < 0)
                {
                    ViewBag.NegNumError = "Please input positive numbers";
                }

                else {
                    
                        double leaseAmountDouble = double.Parse(LeaseAmount);
                        double initialPaymentDouble = double.Parse(InitialPayment);
                        double leasePeriodMonthsDouble = double.Parse(LeasePeriodMonths);
                        double monthlyPaymentsDouble = double.Parse(MonthlyPayments);
                        double initialFilingFeeDouble = double.Parse(InitialFilingFee);
                        
                        double Tax = initialFilingFeeDouble;
                        double totalTaxes = initialFilingFeeDouble;

                        decimal GPR;

                    /*Taxes calc %:*/
                    //double totalTaxes = leaseAmountDouble * (initialFilingFeeDouble / 100);

                    if (!FlatOrPercent)
                    {
                        totalTaxes = leaseAmountDouble * (initialFilingFeeDouble / 100);
                    }

                    double totalPaid = totalTaxes + initialPaymentDouble + (monthlyPaymentsDouble * leasePeriodMonthsDouble);

                        double interestGPR = Microsoft.VisualBasic.Financial.Rate(leasePeriodMonthsDouble, -monthlyPaymentsDouble, (double)(leaseAmountDouble - initialPaymentDouble - totalTaxes)) * 12;
                        GPR = (decimal)Math.Pow((interestGPR / 12) + 1.0, 12) - 1;

                        ViewBag.GPR = Math.Round(GPR * 100, 2, MidpointRounding.AwayFromZero);
                        ViewBag.totalPaidWithTaxes = totalPaid;
                        ViewBag.totalTaxes = totalTaxes;

                        /*Изчислявам го като процен оскъпяване спрямо цената на стоката*/


                        return View();
                }


            }
            catch (ArgumentNullException ex)
            {
                string emptyValueError = ex.Message;
                ViewBag.ErrorMessageEmpty = "Please input a number and try again";
            }
            catch (FormatException ex)
            {
                string formatError = ex.Message;
                ViewBag.ErrorFormat = "Please enter numeric values only and try again";
            }


            return View();
        }

    }
}

FinanceCalculators/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Home</title>
    <meta name="viewport" content="width=device-width initial-scale=1" />
    <link rel="stylesheet" href="/css/home.css">
    <link rel="stylesheet" href="/css/styles.css" />
    @*<link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />*@

    <link rel="icon" href="/Content/Assets/head-logo.jpeg" type="image/png">
</head>

<body>
    <div class="navigation">
        <div class="main-logo">
            <a href="http://localhost:5000"><img src="/Content/Assets/logo.png" class="main-logo-image"></a>
        </div>
    </div>

    <div class="header">
        <div class="text">
            <h2>Ние ви помагаме да <span style="color: var(--primary);">изградите</span><br>вашите мечти.</h2>
            <br>
            <h3>Мисията ни е да помагаме на хората да взимат информирани финансови решения.</h3>
        </div>

        <div class="main-image">
            <img src="/Content/Assets/main-image.png">
        </div>
    </div>

    <div class="centered-text">
        <p>КАЛКУЛАТОРИ</p>
    </div>

    <div class="slideshow-container">

        <div class="slide slideFade">
            <a asp-controller="Credit" asp-action="CreditCalc">
                <img src="/Content/Assets/credit.png">
            </a>
        </div>

        <div class="slide slideFade">
            <a asp-action="RefinanceCalc">
                <img src="/Content/Assets/refinancing.png">
            </a>
        </div>

        <div class="slide slideFade">
            <a asp-controller="Leasing" asp-action="LeaseCalc">
                <img src="/Content/Assets/leasing.png">
            </a>
        </div>

        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>

    <br>
    <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
    </div>

    <script>var slideIndex = 1;
        showSlides(slideIndex);

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        function currentSlide(n) {
            showSlides(slideIndex = n);
        }

        function showSlides(n) {

            // Improve ugly logic
            // Move JS logic in separate file

            var i;
            var slides = document.getElementsByClassName("slide");
            var dots = document.getElementsByClassName("dot");
            if (n > slides.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = slides.length }
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }

            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }

            slides[slideIndex - 1].style.display = "flex";
            dots[slideIndex - 1].className += " active";
        }

        function executeNextSlide() {

            plusSlides(1);
            setTimeout(executeNextSlide, 5000);
        }

        setTimeout(executeNextSlide, 5000);
    </script>

    <div class="footer">

        <div class="footer-column footer-logo">
            <img src="/Content/Assets/second-logo.png">
            <p classs="main-text"> ул. “Монтевидео” 21, 1618 <br> ж.к. Овча Купел 2, Sofia</p>
        </div>

        <div class="footer-column footer-pig">
            <img src="/Content/Assets/footer-illustration.png" class="footer-image">
        </div>

        <div class="footer-column footer-text">
            <p classs="main-text">© 2020 Нов Български Университет</p>
        </div>
    </div>
</body>
</html>

FinanceCalculators/Views/Home/RefinanceCalc.cshtml
<!DOCTYPE html>
@model PartyInvites.Models.RefinanceModel
<!--@{ Layout = null; }-->
<!--TODO: InitialFilingFee flat or percent???; Outputs not done; HTML validation;-->

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8">
    <title>Refinancing Calculator</title>

    <link rel="stylesheet" href="/css/refinancingcal.css"><!--leasingcal.css?-->
    <link rel="stylesheet" href="/css/styles.css" />
    <!--<link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" /> -->

    <link rel="icon" href="/Content/Assets/head-logo.jpeg" type="image/png">
</head>


<body>

    <div class="navigation">
        <div class="main-logo">
            <a href="http://localhost:5000"><img src="/Content/Assets/logo.png" class="main-logo-image"></a>
        </div>
    </div>

    </br>
    </br>

    <label for="section-title" class="section-title">Калкулатор за рефинансиране</label>
    </br>
    <label for="section-mini-title" class="section-mini-title">Пресметнете дали рефинансирането на задълженията Ви е изгодно</label>

    </br>
    </br>
    <!--Refinancing Calculator Fields-->
    <div class="main-container">
        <label for="section-title" class="section-title">Настоящ кредит</label>
        <!--below <form> only concernes View <-> Controller relationship-->
        <form asp-controller="Refinancing" asp-action="RefinanceCalc" method="post" class="m-2">
            <div class="float-container">
                <div class="float-child-left">
                    <div class="input-wrapper">
                        <input type="number" asp-for="CreditAmount" asp-controller="Refinancing" asp-action="RefinanceCalc" name="CreditAmount" placeholder="Размер на кредита*" required id="size" min="100" max="100000000"><br>
                    </div>
                </div>

                <div class="float-child-right">
                    <div class="input-wrapper">
                        <input type="number" asp-for="InterestRatePercentage" asp-controller="Refinancing" asp-action="RefinanceCalc" name="InterestRatePercent" placeholder="Лихва (%)*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>

                <div class="float-child-left">
                    <div class="input-wrapper">
                        <input type="number" asp-for="CreditTermMonths" asp-controller="Refinancing" asp-action="RefinanceCalc" name="CreditTermMonths" placeholder="Срок на кредита (месеци)*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>

                <div class="float-child-right">
                    <div class="input-wrapper">
                        <input type="number" asp-for="NumberOfPaymentsMade" asp-controller="Refinancing" asp-action="RefinanceCalc" name="NumberOfPaymentsMade" placeholder="Брой на направените вноски*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>

                <div class="dropdown-child">
                    <div class="input-wrapper">
                        <input type="number" asp-for="EarlyRepaymentTax" asp-controller="Refinancing" asp-action="RefinanceCalc" name="EarlyRepaymentTax" placeholder="Такса за предсрочно погасяване*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>
            </div>

            <label for="section-title" class="section-title">Нов кредит</label>

            <div class="float-container">

                <div class="float-child-left">
                    <div class="input-wrapper">
                        <input type="number" asp-for="InitialTaxes" asp-controller="Refinancing" asp-action="RefinanceCalc" name="NewCreditInitialTaxesPecent" placeholder="Първоначални такси*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>

                <div class="float-child-right">
                    <select asp-for="InitialTaxesFlatOrPercentage" name="ApplicationFeeFlatOrPercentage" asp-controller="Refinancing" asp-action="RefinanceCalc" class="selector">
                        <option value="true">валута</option>
                        <option value="false">%</option>
                    </select>
                </div>

                <div class="dropdown-child">
                    <div class="input-wrapper">
                        <input type="number" asp-for="InterestRate" asp-controller="Refinancing" asp-action="RefinanceCalc" name="NewCreditInterest" placeholder="Лихва*" required id="size" min="10" max="100000000"><br>
                    </div>
                </div>
            </div>

            <!--onclick="myFunction()"-->
            <div class="button-container" formmethod="post" type="submit" id="lease" value="lease" name="calculate">
                <button asp-controller="Refinancing" asp-action="RefinanceCalc" formmethod="post" type="submit" class="calculate-button" id="Refinancing" value="Refinancing" name="Refinancing">Изчисли</button>
            </div>

        </form>
    </div>

    <!--style="display: none-->
    <div id="result-table" class="result-table">

        <label for="section-mini-title" class="section-mini-title">Резултати</label>
        </br>

        <table>
            <tr>
                <td>Резултат</td>
                <td>Текущ кредит</td>
                <td>Нов кредит</td>
                <td>+/- Спестявания</td>
            </tr>
            <tr>
                <td>Лихва</td>
                <td>@ViewBag.interestRate</td>
                <td>@ViewBag.interestRateNew</td>
                <td></td>
            </tr>
            <tr>
                <td>Срокове на кредитите</td>
                <td>@ViewBag.creditTermOld</td>
                <td>@ViewBag.creditTermNew</td>
                <td></td>
            </tr>
            <tr>
                <td>Такса за предсрочно погасяване</td>
                <td>@ViewBag.earlyRepaymentTax</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Месечна вноска</td>
                <td>@ViewBag.monthlyPaymentOld</td>
                <td>@ViewBag.monthlyPaymentNew</td>
                <td>@ViewBag.savingsOnMonthly</td>
            </tr>
            <tr>
                <td>Общо изплатени</td>
                <td>@ViewBag.totalPaidOld</td>
                <td>@ViewBag.totalPaidNew</td>
                <td>@ViewBag.savingsOnTotal</td>
            </tr>
        </table>
    </div>
    <br>

    <!--Margin to be removed-->
    <div class="section-footer-description">
        <label>
            * Задължителни полетa </br> </br>
            C пoмoщтa нa ĸaлĸyлaтopa зa peфинaнcиpaнe нa ĸpeдити мoжeтe дa изчиcлитe ĸoлĸo биxтe cпecтили/изгyбили, aĸo peшитe дa peфинaнcиpaтe, т.e. дa изтeглитe нoв ĸpeдит, зa дa пoгacитe cтapo ĸpeдитнo зaдължeниe.
            Зa цeлтa тpябвa дa въвeдeтe cлeднитe дaнни зa нacтoящия Bи ĸpeдит – paзмep, гoдишeн лиxвeн пpoцeнт, cpoĸ нa ĸpeдитa, бpoй нa нaпpaвeнитe внocĸи пo нeгo дo мoмeнтa, ĸaĸтo и paзмepa нa нaĸaзaтeлнaтa лиxвa зa пpeдcpoчнo пoгacявaнe.</br></br> Heoбxoдимитe дaнни зa нoвият ĸpeдит ca лиxвeн пpoцeнт и дължими тaĸcи и ĸoмиcиoнни нa бaнĸaтa пo oтпycĸaнeтo нa ĸpeдитa.
            Kaлĸyлaтopът изчиcлявa двe cтoйнocти, пo ĸoитo мoжeтe дa ce opиeнтиpaтe дaли peфинaнcиpaнeтo e изгoднo зa Bac – paзлиĸa мeждy мeceчнитe внocĸи пo двaтa ĸpeдитa и мeждy oбщo изплaтeнитe cyми.
        </label>
    </div>

    <div class="footer">

        <div class="footer-column footer-logo">
            <img src="/Content/Assets/second-logo.png">
            <p classs="main-text"> ул. “Монтевидео” 21, 1618 <br> ж.к. Овча Купел 2, Sofia</p>
        </div>

        <div class="footer-column footer-pig">
            <img src="/Content/Assets/footer-illustration.png" class="footer-image">
        </div>

        <div class="footer-column footer-text">
            <p classs="main-text">© 2020 Нов Български Университет</p>
        </div>
    </div>

    <!--
    <script>

        function myFunction() {

            console.log("Lead me to the BE , calculate result & come back.")

            var tb = document.getElementById("result-table");

            if (tb.style.display == "none") {
                tb.style.display = "grid";
            }
        }

    </script>
        -->
</body>

</html>